core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('mentorados/', include('mentorados.urls')),
    path('reunioes/', include('reunioes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentorados/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mentorados, name='mentorados'),
    path('auth/', views.auth, name="auth_mentorado"),
]

reunioes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.reunioes, name='reunioes'),
]

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/',views.cadastro, name='cadastro'),
    path("login/", views.login, name="login"),
]

mentorados/models.py
from datetime import timedelta
import secrets
from django.db import models
from django.contrib.auth.models import User 

# To create the database table for the Navigators model, run:
# py manage.py makemigrations

class Navigators(models.Model):
    nome = models.CharField(max_length=255) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

# Create your models here.
class Mentorados(models.Model):
    estagio_choices = (
        ("E1", "10-100K"),
        ("E2", "100-1MM"),
    )

    nome = models.CharField(max_length=255)
    estagio = models.CharField(max_length=2, choices=estagio_choices)
    foto = models.ImageField(upload_to='fotos', null=True, blank=True)

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    token = models.CharField(max_length=16, null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    navigators = models.ForeignKey(Navigators, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.nome
    
    def save(self, *args, **kwargs):
        if not self.token: 
            self.token = self.gerar_token_unico()
        super().save(*args, **kwargs)

    def gerar_token_unico(self):
        while True:
            token = secrets.token_urlsafe(8)  
            if not Mentorados.objects.filter(token=token).exists():
                return token


class DisponibilidadeHorarios(models.Model):
    data_inicial = models.DateTimeField(null=True, blank=True)
    mentor = models.ForeignKey(User, on_delete=models.CASCADE)
    agendado = models.BooleanField(default=False)

    @property
    def data_final(self):
        return self.data_inicial + timedelta(minutes=50)
    
class Reuniao(models.Model):
    tag_choices = (
        ('G', 'Gestão'),
        ('M', 'Marketing'),
        ('RH', 'Gestão de pessoas'),
        ('I', 'Impostos')
    )

    data = models.ForeignKey(DisponibilidadeHorarios, on_delete=models.CASCADE)
    mentorado = models.ForeignKey(Mentorados, on_delete=models.CASCADE)
    tag = models.CharField(max_length=2, choices=tag_choices)
    descricao = models.TextField()

reunioes/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models

mentorados/views.py
from django.shortcuts import render, redirect
from django.core.handlers.wsgi import WSGIRequest
from django.contrib import messages
from django.contrib.messages import constants

from mentorados.models import Navigators, Mentorados

# Create your views here.
def mentorados(request: WSGIRequest):
    if not request.user.is_authenticated:
        return redirect("login")
    
    if request.method == 'GET':
        navigators = Navigators.objects.filter(user=request.user)
        mentorados = Mentorados.objects.filter(user=request.user)
        
        estagios_flat = [i[1] for i in Mentorados.estagio_choices]
        qtd_estagios = []
        for i, _ in Mentorados.estagio_choices:
            qtd_estagios.append(Mentorados.objects.filter(estagio=i).count())

        return render(request, 'mentorados.html', {'estagios': Mentorados.estagio_choices, 'navigators': navigators, 'mentorados': mentorados, 'estagios_flat': estagios_flat, 'qtd_estagios': qtd_estagios})

    elif request.method == 'POST':
        nome = request.POST.get('nome')
        foto = request.FILES.get('foto')
        estagio = request.POST.get("estagio")
        navigator = request.POST.get('navigator')

        mentorado = Mentorados(
            nome=nome,
            foto=foto,
            estagio=estagio,
            navigators_id=navigator,
            user=request.user
        )

        mentorado.save()
        messages.add_message(request, constants.SUCCESS, 'Mentorado cadastrado com sucesso.')
        return redirect('mentorados')

reunioes/views.py
from datetime import datetime, timedelta
from django.shortcuts import render
from mentorados.models import DisponibilidadeHorarios, Mentorados
from django.contrib import messages
from django.contrib.messages import constants
from django.shortcuts import redirect
from django.core.handlers.wsgi import WSGIRequest


# Create your views here.
def reunioes(request: WSGIRequest):
    if request.method == 'GET':
        return render(request, 'reunioes.html')
    else:
        data = request.POST.get('data')

        data = datetime.strptime(data, '%Y-%m-%dT%H:%M')

        disponibilidades = DisponibilidadeHorarios.objects.filter(
            data_inicial__gte=(data - timedelta(minutes=50)),
            data_inicial__lte=(data + timedelta(minutes=50))
        )

        if disponibilidades.exists():
            messages.add_message(request, constants.ERROR, 'Você já possui uma reunião em aberto.')
            return redirect('reunioes')

        disponibilidade = DisponibilidadeHorarios(
            data_inicial=data,
            mentor=request.user

        )
        disponibilidade.save()

        messages.add_message(request, constants.SUCCESS, 'Horário disponibilizado com sucesso.')
        return redirect('reunioes')
    

def auth(request: WSGIRequest):
    if request.method == 'GET':
        return render(request, 'auth_mentorado.html')
    else:
        token = request.POST.get('token')

        if not Mentorados.objects.filter(token=token).exists():
            messages.add_message(request, constants.ERROR, 'Token inválido')
            return redirect('auth_mentorado')
        
        response = redirect('escolher_dia')
        response.set_cookie('auth_token', token, max_age=3600)
        return response

usuarios/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.handlers.wsgi import WSGIRequest

from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import auth
from django.contrib.messages import constants 
from django.contrib import messages


# Create your models here.
def cadastro(request: WSGIRequest):
    if request.method == 'GET':
        return render(request, 'cadastro.html')
    
    username = request.POST.get('username')
    senha = request.POST.get('senha')
    confirmar_senha = request.POST.get('confirmar_senha')

    if not senha == confirmar_senha:
        messages.add_message(request, constants.ERROR, 'As senhas não conferem')
        return redirect('/usuarios/cadastro')
    
    if len(senha) < 6:
        messages.add_message(request, constants.ERROR, 'A senha deve ter no mínimo 6 caracteres')
        return redirect('/usuarios/cadastro')

    users = User.objects.filter(username=username)

    if users.exists():
        messages.add_message(request, constants.ERROR, 'Já existe um usuário com esse nome')
        return redirect('/usuarios/cadastro')
    
    User.objects.create_user(
        username=username,
        password=senha
    )

    return redirect('/usuarios/login')



def login(request: WSGIRequest):
    if request.method == 'GET':
        return render(request, 'login.html')
    
    username = request.POST.get('username')
    senha = request.POST.get('senha')

    user = authenticate(request, username=username, password=senha)

    if user:
        auth.login(request, user)
        return redirect('/mentorados/')
    
    messages.add_message(request, constants.ERROR, 'Username ou senha inválidos')
    return redirect('login')

mentorados/templates/auth_mentorado.html
{% extends "base.html" %}

{% block 'body' %}
    <div class="bg-gray-900 flex items-center justify-center h-screen">
        <div class="bg-gray-800 p-8 rounded-lg shadow-lg text-center w-96">
            <form action="{% url 'auth_mentorado' %}" method="POST"> {% csrf_token %}
                
                <h2 class="text-2xl font-bold text-gray-200 mb-4">Acessar conteúdo</h2>
                {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <label class="text-gray-400 block text-left mb-1">Token de acesso</label>
                <input type="text" name="token" class="w-full p-3 rounded-md bg-gray-300 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="Digite seu token">

                <button class="w-full mt-4 bg-indigo-600 text-white font-semibold p-3 rounded-md hover:bg-indigo-700 transition cursor-pointer">Acessar</button>
            </form>
        </div>
    </div>
{% endblock 'body' %}

mentorados/templates/mentorados.html
{% extends "base.html" %}
{% load static %}

{% block 'body' %}
<header class="bg-slate-900">
    <nav class="flex items-center justify-between p-4 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Mentorados</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Tarefas</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Progressos</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Navigators</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        
      </div>
    </nav>
    
    </div>
  </header>
  
 
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto py-12">
        <div class="grid grid-cols-2 gap-4">
            <div>
                <form action="{% url 'mentorados' %}" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Cadastre seus mentorados</h2> 
                {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <div>
                    <label for="email" class="block text-sm/6 font-medium text-gray-200">Nome</label>
                    <div class="mt-2">
                        <input type="text" name="nome" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                      </div>
                </div>
                <div class="grid grid-cols-2 gap-4 mt-4">
                    <div>
                        <label class="block text-sm/6 font-medium text-gray-200">Foto</label>
                        <div class="mt-2">
                            <input type="file" name="foto" id="foto" autocomplete="foto" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                        </div>
                    </div>
                    <div>
                        <label class="block text-sm/6 font-medium text-gray-200">Estágio</label>
                        <div class="mt-2">
                            <select name="estagio" id="" class="block w-full rounded-md bg-white/5 px-3 py-2 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                                {% for estagio in estagios  %}
                                    <option class="text-slate-900" value="{{estagio.0}}">{{estagio.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="mt-4">
                        <label class="block text-sm/6 font-medium text-gray-200">Navigator</label>
                        <div class="mt-2">
                            <select name="navigator" id="" class="block w-full rounded-md bg-white/5 px-3 py-2 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                                {% for navigator in navigators  %}
                                    <option value="{{navigator.id}}">{{navigator.nome}}</option>  
                                {% endfor %}   
                            </select>
                        </div>
                        <br>
                        <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cadastrar</button>
                </div>
              </form>
            </div>

            <div class="flex justify-center items-center w-1/2 mx-auto">
                <canvas id="myChart" class="w-24 h-24"></canvas>
            </div>


        </div>
        <div class="mt-6">
            <hr class="border-gray-600">
            <br>    
            <h2 class="text-base/7 font-semibold text-white ">Seus mentorados</h2>
            <table class="mt-6 w-full whitespace-nowrap text-left">
              <colgroup>
                <col class="w-full sm:w-4/12">
                <col class="lg:w-4/12">
                <col class="lg:w-2/12">
                <col class="lg:w-1/12">
                <col class="lg:w-1/12">
              </colgroup>
              <thead class="border-b border-white/10 text-sm/6 text-white">
                <tr>
                  <th scope="col" class="py-2 pl-4 pr-8 font-semibold sm:pl-6 lg:pl-8">Usuário</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold sm:table-cell">Estágio</th>
                  <th scope="col" class="py-2 pl-0 pr-4 text-right font-semibold sm:pr-8 sm:text-left lg:pr-20">Status</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Data entrada</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Navigator</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-white/5">
                
               
                {% for mentorado in mentorados %}
                <tr>
                  <td class="py-4 pl-4 pr-8 sm:pl-6 lg:pl-8">
                    <div class="flex items-center gap-x-4">
                      <img src="{{mentorado.foto.url}}" alt="" class="size-8 rounded-full bg-gray-800">
                      <div class="truncate text-sm/6 font-medium text-white">{{mentorado.nome}}</div>
                    </div>
                  </td>
                  <td class="hidden py-4 pl-0 pr-4 sm:table-cell sm:pr-8">
                    <div class="flex gap-x-3">
                      <div class="rounded-md bg-gray-700/40 px-2 py-1 text-xs font-medium text-gray-400 ring-1 ring-inset ring-white/10">{{mentorado.get_estagio_display}}</div>
                    </div>
                  </td>
                  <td class="py-4 pl-0 pr-4 text-sm/6 sm:pr-8 lg:pr-20">
                    <div class="flex items-center justify-end gap-x-2 sm:justify-start">
                      <div class="flex-none rounded-full bg-green-400/10 p-1 text-green-400">
                        <div class="size-1.5 rounded-full bg-current"></div>
                      </div>
                      <div class="hidden text-white sm:block">Ativo</div>
                    </div>
                  </td>
                  <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">{{mentorado.criado_em}}</td>
                  <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">
                   
                    {{mentorado.navigators.nome}}
                    
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>

    </div>
     
  </div>

  <script src="/static/chart.js"></script>

  <script>
    const ctx = document.getElementById('myChart');

    new Chart(ctx, {
      type: 'pie',
      data: {
        labels: {{estagios_flat|safe}},
        datasets: [{
          label: '',
          data: {{qtd_estagios|safe}},
          borderWidth: 1
        }]
      },
      
    });
  </script>
{% endblock 'body' %}

reunioes/templates/reunioes.html
{% extends "base.html" %}
{% load static %}

{% block 'body' %}
<header class="bg-slate-900">
    <nav class="flex items-center justify-between p-4 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Mentorados</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Tarefas</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Progressos</a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">Navigators</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        
      </div>
    </nav>
  </header>
  
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto py-8">
        <div class="grid grid-cols-2 gap-12 ">
            <div>
              {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'reunioes' %}" method="POST">{% csrf_token %}
                  <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Abra um horário</h2>
                  <label for="email" class="block text-sm/6 font-medium text-gray-200">Data</label>
                  <input type="datetime-local" name="data" id="date" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                  
                  <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mt-4">Abrir horários</button>
                </form>

            </div>
            <div>
              
                
                <ul role="list" class="divide-y divide-gray-800">
                   
                    <li class="flex justify-between gap-x-6 py-5">
                      <div class="flex min-w-0 gap-x-4">
                        <img class="size-12 flex-none rounded-full bg-gray-800" src="#" alt="">
                        <div class="min-w-0 flex-auto">
                          <p class="text-sm/6 font-semibold text-white">Nome</p>
                          <p class="mt-1 truncate text-xs/5 text-gray-400">Descricao</p>
                        </div>
                      </div>
                      <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
                        <p class="text-sm/6 text-white">Data</p>
                        <p class="mt-1 text-xs/5 text-gray-400"></p>
                      </div>
                    </li>
                    
                  </ul>
                  
            </div>
        </div>

    </div>
  </div>

{% endblock 'body' %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Monitorando</title>
    {% comment %} <script src="https://unpkg.com/@tailwindcss/browser@4"></script> {% endcomment %}
    <script src="/static/tailwind-4.1.3.global.js"></script>
    {% block 'head' %}{% endblock 'head' %}
</head>
<body>
    {% block 'body' %}{% endblock 'body' %}
</body>
</html>

usuarios/templates/cadastro.html
{% extends "base.html" %}
{% block 'body' %}
{% load static %}

<div class="flex min-h-screen bg-slate-900">
    <div class="flex flex-1 flex-col justify-center px-4 py-12 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
      <div class="mx-auto w-full max-w-sm lg:w-96">
        <div>
          
          <img class="h-15 w-auto" src="{% static 'logo.png' %}" alt="Logo">

          <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Crie sua conta</h2>
          <p class="mt-2 text-sm/6 text-gray-500">
            Já tem uma conta?
            <a href="{% url 'login' %}" class="font-semibold text-indigo-300 hover:text-indigo-200">Faça login</a>
          </p>
          {% if messages %}
              {% for message in messages %}
                  <div class="rounded-md bg-green-50 text-green-700 {{message.tags}} mt-4">
                      <div class="flex">
                          <div class="ml-3 py-4">
                              {{message}}
                          </div>
                      </div>
                  </div>
              {% endfor %}
          {% endif %}
        </div>
  
        <div class="mt-8">
          <div>
            <form action="{% url 'cadastro' %}" method="POST" class="space-y-6">{% csrf_token %}
              <div>
                <label for="email" class="block text-sm/6 font-medium text-gray-200">Username</label>
                <div class="mt-2">
                    <input type="text" name="username" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                  </div>
              </div>
  
              <div>
                <label for="password" class="block text-sm/6 font-medium text-gray-200">Senha</label>
                <div class="mt-2">
                    <input type="password" name="senha"  required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                  </div>
              </div>
              <div>
                <label for="password" class="block text-sm/6 font-medium text-gray-200">Confirmar senha</label>
                <div class="mt-2">
                    <input type="password" name="confirmar_senha" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                  </div>
              </div>
  
  
              <div>
                <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cadastrar</button>
              </div>
            </form>
          </div>
  
          
        </div>
      </div>
    </div>
    <div class="relative hidden w-0 flex-1 lg:block">
      <img class="absolute inset-0 size-full object-cover" src="{% static 'cadastro-background.jfif' %}" alt="Pessoas">
    </div>
  </div>

{% endblock 'body' %}

usuarios/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
<div class="flex min-h-screen bg-slate-900">
    <div class="flex flex-1 flex-col justify-center px-4 py-12 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
      <div class="mx-auto w-full max-w-sm lg:w-96">
        <div>
          <img class="h-15 w-auto" src="{% static 'logo.png' %}" alt="Your Company">
          <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Entre em sua conta</h2>
          <p class="mt-2 text-sm/6 text-gray-500">
            Não tem conta?
            <a href="{% url 'cadastro' %}" class="font-semibold text-indigo-300 hover:text-indigo-200">Crie sua conta aqui</a>
          </p>

          {% if messages %}
              {% for message in messages %}
                  <div class="rounded-md {{message.tags}} mt-4">
                      <div class="flex">
                          <div class="ml-3 py-4">
                              {{message}}

                          </div>

                      </div>
                  </div>
              {% endfor %}
          {% endif %}
        </div>
  
        <div class="mt-8">
          <div>
            <form action="{% url 'login' %}" method="POST" class="space-y-6">{% csrf_token %}
              <div>
                <label class="block text-sm/6 font-medium text-gray-200">Username</label>
                <div class="mt-2">
                    <input type="text" name="username" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                  </div>
              </div>
  
              <div>
                <label for="password" class="block text-sm/6 font-medium text-gray-200">Senha</label>
                <div class="mt-2">
                    <input type="password" name="senha" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                  </div>
              </div>
  
  
              <div>
                <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Entrar</button>
              </div>
            </form>
          </div>
  
          
        </div>
      </div>
    </div>
    <div class="relative hidden w-0 flex-1 lg:block">
      <img class="absolute inset-0 size-full object-cover" src="https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
     
    </div>
  </div>

{% endblock 'body' %}